/*
 * HOGBasedSvm_jni.h
 *
 *  Created on: Jun 7, 2014
 *      Author: developer
 */


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

#ifndef HOGBASEDSVM_JNI_H_
#define HOGBASEDSVM_JNI_H_

#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jlong JNICALL Java_org_opencv_samples_facedetect_HOGBasedSvm_nativeCreateHog
(JNIEnv * jenv, jclass, jstring jFileName);


JNIEXPORT jfloat JNICALL Java_org_opencv_samples_facedetect_HOGBasedSvm_nativePredict
(JNIEnv * jenv, jclass ,jlong thiz, jlong imgGrayAddr);


#ifdef __cplusplus
}
#endif
#endif

